config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'session/new', to: "session#new"
  get '/forgetpassword', to: "forgot_password#new"
  post '/forgetpassword', to: "forgot_password#find_user"
  resources :users
  resources :session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

	belongs_to :project_owner,-> {where(role: "project_owner")}, class_name: "User"
	# has_many :created_tasks, foreign_key: :task_project_id, class_name: "Task"

	#belongs_to :user
	has_many :tasks, foreign_key: :task_project_id
	has_many :user_task, foreign_key: :assigned_task_id
	



	#validations
	validates :name, :start_date, :end_date, presence: true

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/task.rb
class Task < ApplicationRecord
	# belongs_to :project_owner, class_name: "User"
	# belongs_to :task_from_project, class_name: "Project"

	belongs_to :user
	belongs_to :project


    #validations
	validates :name, :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_developer_id
  rolify
  has_secure_password
  mount_uploader :image, ImageUploader
   has_many :created_projects, foreign_key: :project_owner_id, class_name: "Project", dependent: :destroy
  # has_many :created_tasks, foreign_key: :task_assigned_user_id, class_name: "Task"
  # has_many :assigned_tasks, through: :created_tasks, source: :project_owner
   
    #has_many :projects 
    has_many :user_tasks, foreign_key: :assigned_user_id
    has_many :task_assigned, through: :user_tasks, source: :assigned_developer



    #validations
    validates :first_name, :last_name, :email, :password, presence: true, on: :create
    validates :email, :uniqueness => { :case_sensitive => false }
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

   private

   def set_developer_id
     if self.role=="developer"

      self.update(developer_id: self.id)
    end
   end

    
end

app/models/user_task.rb
class UserTask < ApplicationRecord
	belongs_to :assigned_developer, class_name: 'User'
	belongs_to :task_project, class_name: 'Project'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
  protect_from_forgery with: :exception

   before_action :set_cache_buster
   
  
  
  private

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

app/controllers/forgot_password_controller.rb
class ForgotPasswordController < ApplicationController
	def new
	end
   
    def find_user
    	debugger

    	@user = User.find_by_email(params[:email])
    	if @user
    		UserMailer.forgot_password(@user).deliver
    		flash[:notice] = "Forget password link sended to yopur email id"
        else
        	flash[:danger] = "please provide valid email"
        	render 'new'
    	end
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
  	user  = User.find_by_email(params[:session][:user_name].downcase)
    #mail = User.find_by_email(params[:session][:user_name].downcase)
  	if user && user.authenticate(params[:session][:password])
  		
  		log_in user
  		flash[:success] = "login success"
  		redirect_to user_path(current_user), sucess: "login success" 
  	   
  	else
  		flash[:danger]  = "invalid user or password..retry again...!!!"
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to new_session_path  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, only: [:show]
   
  def new
  	@user = User.new
  end

  def create
  	
    @user  = User.new(user_params)
    
  	if @user.save
      #check_role(@user)
      UserMailer.signup_confirmation(@user).deliver
  	  redirect_to @user
  	else
  	  render 'new'
  	end
  	
  end

  
  def show
  	@user = current_user
  	 
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name,:image, :email, :password, :role )
  end
  def check_login
    if logged_in?
    else
      
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forgot_password_helper.rb
module ForgotPasswordHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def log_in(user)
      session[:user_id] = user.id
		
    end

    def current_user
  	  @current_user ||= User.find_by(id: session[:user_id])
  	
    end

   def logged_in?
    !current_user.nil?

  end

  
  def log_out
  	session.delete(:user_id) 
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forgot_password/new.html.erb
<%= form_tag(forgetpassword_path, method: :post) do%>
<%= label_tag :email, "enter your registered mail"%><br/>
<%= text_field_tag :email%>
<br/>
<%= submit_tag "send link"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagementTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/_signform.html.erb
<%= form_for(:session, url: session_index_path) do|f| %>
  <p>
    <%= f.label :login, "Username/Email" %><br />
    <%= f.text_field :user_name%>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Log in" %>
  <%= link_to "forgot password", forgetpassword_path %></p>
<% end %>
<p> New user?<%= link_to "sign up", new_user_path%>

app/views/session/new.html.erb
<%= render 'session/signform' %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %> <% if @user.errors.any? %>
<%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:

    <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
    <% end %> 

<% end %>

<%= f.label :first_name%><br/>
<%= f.text_field :first_name %><br/>

<%= f.label :last_name %><br/>
<%= f.text_area :last_name %>
<br/>
<%= f.label :email%><br/>
<%= f.text_area :email %><br/>

<%= f.label :image %>
<%= f.file_field :image %><br/>


<%= f.label :password %><br/>
<%= f.password_field :password %><br/>

<%= f.label :password_confirmation, "Confirm Password" %><br/>
<%= f.password_field :password_confirmation %><br/>

<%= f.select :role, options_for_select([["Select One", ""], "project owner", "developer", "Both"]) %>
<%= f.submit "sign up" %><br/>
<% end %>

<%= link_to "Registered user", new_session_path %>